### ISSUE TITLE
Expand references before passing config to dataset and model

### ISSUE THREAD

**Issue by FloopCZ** [Cognexa/cxflow#203]
Otherwise we are not properly parsing YAML config.

We also cannot easily share config between the `model` and the `dataset` sections.

```yaml
shared: &SHARED
  item: shared_data
  
dataset:
  <<: *SHARED
  specific_item: value

model:
  <<: *SHARED
  specific_item: value
```
