### ISSUE TITLE
Allow prediction of any stream

### ISSUE THREAD

**Issue by FloopCZ** [Cognexa/cxflow#220]
Following up todays discussion with @blazekadam.

Prediction CLI syntax should look as follows:
`cxflow predict <stream>`
and the predict section in the config file should look as follows:
```
predict:
  valid:
    dataset: ...
    model: ...
    hooks: ...
  production:
    dataset: ...
    model: ...
    hooks: ...
```

The reasons are obvious.
