### ISSUE TITLE
"Argument was not recognized" invalid warning when constructing some hooks

### ISSUE THREAD

**Issue by bedapisl** [Cognexa/cxflow#239]
When training model and using DecayLROnPlateau with this setting:
```
hooks:
- cxflow_tensorflow.hooks.DecayLROnPlateau:
    long_term: 200
    short_term: 100
```
cxflow gives following warnings:
```
2018-09-19 09:39:43.364: WARNING @abstract_hook: Argument `long_term` was not recognized by `DecayLROnPlateau`. Recognized arguments are `['decay_value', 'kwargs']`.
2018-09-19 09:39:43.364: WARNING @abstract_hook: Argument `short_term` was not recognized by `DecayLROnPlateau`. Recognized arguments are `['decay_value', 'kwargs']`.
```
although the warnings are not valid.
