### ISSUE TITLE
Flatten `net.io` config

### ISSUE THREAD

**Issue by blazekadam** [Cognexa/cxflow#53]
At the moment, net inputs/outputs are defined as a dict of list of strings, e.g.:
```yaml
 io:
    in: [images, labels]
    out: [loss, predictions, dice]
```

I suggest to flatten this structure, e.g.:
```yaml
inputs: [images, labels]
outputs: [loss, predictions, dice]
```

The reason is that the net constructor is often called from python code (tests, net restoring) and its complicated and confusing to specify the dict structure.
