### ISSUE TITLE
Remove `Hook` from hook names

### ISSUE THREAD

**Issue by blazekadam** [Cognexa/cxflow#55]
I suggest to omit `Hook` in hook names. E.g. name the logging hook as `Log` or `Logging` instead of `LoggingHook`.

With this change, the configs may be more readable, e.g.:
```yaml
-hooks
  - class: ComputeStats
    variables:
      dice: [mean]
      loss: [mean]
  - class: WriteCSV
  - class: LogVariables
  - class: LogProfile
  - class: CaptureSigint
  - class: SaveBest

```

The hooks are referenced either from the configs or the python code. In both cases, it is clear that they are hooks as the reference is in the `hooks` section or via `from cxflow.hooks import...` respectively.

**Comment by blazekadam** [comment]
Also, we may omit the the `class` key-word in the case that the module is not specified, e.g.:
```yaml
-hooks
  - ComputeStats
    variables:
       dice: [mean]
       loss: [mean]
  - WriteCSV
  - LogVariables
  - LogProfile
  - CaptureSigint
  - SaveBest

```

**Comment by blazekadam** [comment]
@petrbel @FloopCZ please comment on this.

**Comment by FloopCZ** [comment]
It will make config parsing slightly more complicated and config file slightly more clear and succinct. I would go for it.

**Comment by petrbel** [comment]
Yes it is pretty nice and clear. Nevertheless, I am still not convinced we want to drop `Hook` suffix from the class names.
I actually like this "type" in the class names (including datasets, nets and others).

**Comment by blazekadam** [comment]
I ll implement the proposed changes.

Unless @FloopCZ is against, I ll drop the `Hook` suffixes.

**Comment by FloopCZ** [comment]
@FloopCZ is not against.

**Comment by blazekadam** [comment]
Is there any reason against specifying fully qualified names instead of module - class pairs.

I would prefer
```yaml
  - cxflow_tensorflow.LRDecayHook
      decay_value: 0.998
```
instead of 
```yaml
  - module: cxflow_tensorflow
    class: LRDecayHook
    decay_value: 0.998
```

@FloopCZ , @petrbel pls comment asap.
